<?php
try{
   // $key_code = Helpers_Utilities::encrypted_key('eHEzSzJGYTNYWG5xV1Yyak9nUFJMUT09', 'decrypt');
    //$con=mysqli_connect("10.10.10.2",'a!&$VpN','$oTal#_pI%4939','@!eSvPn');
    
    $con=mysqli_connect("192.168.1.100","ims","123456789","aies");
    
     //$con=mysqli_connect("10.10.10.2","aiesremote",$key_code,"aies");

    //$con=mysqli_connect("192.168.0.126","aies","8abc1234567","aies_vpn");
} catch (Exception $e)
{
    exit;
}





?> 